language: node_js
dist: bionic
os: linux

stages:
  - Kibana Plugin

services:
  - docker

jobs:
  include:
    - stage: Kibana Plugin
      name: Lint
      script: chown -R 1000:1000 . && docker-compose -f dockerfiles/docker-compose.yml run kibana-plugin-ci /scripts/lint.sh
    - name: Test
      script: chown -R 1000:1000 . && docker-compose -f dockerfiles/docker-compose.yml run kibana-plugin-ci /scripts/test.sh