---
version: '3.5'

services:
  elas01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    env_file: docker/elasticsearch.env
    deploy:
      endpoint_mode: dnsrr
    environment:
      - node.name=elas01
      - discovery.seed_hosts=elas02,elas03
    volumes:
      - ./docker/build-certs/pki/intermediate/certs/elas01.cert.pem:/usr/share/elasticsearch/config/pki/elas.cert.pem
      - ./docker/build-certs/pki/intermediate/private/elas01.key.pem:/usr/share/elasticsearch/config/pki/elas.key.pem
      - ./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem:/usr/share/elasticsearch/config/pki/ca.cert.pem
      - ./docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elastic-healthcheck.sh:/bin/elastic-healthcheck.sh
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: /bin/elastic-healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 5
  elas02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    env_file: docker/elasticsearch.env
    deploy:
      endpoint_mode: dnsrr
    environment:
      - node.name=elas02
      - discovery.seed_hosts=elas01,elas03
    volumes:
      - ./docker/build-certs/pki/intermediate/certs/elas02.cert.pem:/usr/share/elasticsearch/config/pki/elas.cert.pem
      - ./docker/build-certs/pki/intermediate/private/elas02.key.pem:/usr/share/elasticsearch/config/pki/elas.key.pem
      - ./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem:/usr/share/elasticsearch/config/pki/ca.cert.pem
      - ./docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elastic-healthcheck.sh:/bin/elastic-healthcheck.sh
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: /bin/elastic-healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 5
  elas03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    env_file: docker/elasticsearch.env
    deploy:
      endpoint_mode: dnsrr
    environment:
      - node.name=elas03
      - discovery.seed_hosts=elas02,elas03
    volumes:
      - ./docker/build-certs/pki/intermediate/certs/elas03.cert.pem:/usr/share/elasticsearch/config/pki/elas.cert.pem
      - ./docker/build-certs/pki/intermediate/private/elas03.key.pem:/usr/share/elasticsearch/config/pki/elas.key.pem
      - ./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem:/usr/share/elasticsearch/config/pki/ca.cert.pem
      - ./docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elastic-healthcheck.sh:/bin/elastic-healthcheck.sh
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: /bin/elastic-healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 5
  logs01:
    image: docker.elastic.co/logstash/logstash:7.5.1
    deploy:
      endpoint_mode: dnsrr
    ports:
      - 5454:5454
    environment:
      - PATH_DATA=/usr/share/logstash/data
      - ELASTICSEARCH_PASSWORD=${LOGSTASH_USER_PASSWORD}
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=https://coordinator:9200
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${LOGSTASH_SYSTEM_PASSWORD}
      - XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITY=/usr/share/logstash/config/pki/ca.cert.pem
    volumes:
      - ./docker/build-certs/pki/intermediate/certs/localhost.cert.pem:/usr/share/logstash/config/pki/logs.cert.pem
      - ./docker/build-certs/pki/intermediate/private/localhost.key.pkcs8:/usr/share/logstash/config/pki/logs.key.pkcs8
      - ./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem:/usr/share/logstash/config/pki/ca.cert.pem
      - ./docker/dynamicbeat-pipeline.conf:/usr/share/logstash/pipeline/dynamicbeat-pipeline.conf
      - data04:/usr/share/logstash/data
    networks:
      - elastic
  kiba01:
    image: docker.elastic.co/kibana/kibana:7.5.1
    deploy:
      endpoint_mode: dnsrr
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./docker/build-certs/pki/intermediate/certs/localhost.cert.pem:/usr/share/kibana/config/pki/kiba.cert.pem
      - ./docker/build-certs/pki/intermediate/private/localhost.key.pem:/usr/share/kibana/config/pki/kiba.key.pem
      - ./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem:/usr/share/kibana/config/pki/ca.cert.pem
      - ./docker/kibana.yml:/usr/share/kibana/config/kibana.yml
      - data05:/usr/share/kibana/data
      - plugins:/usr/share/kibana/plugins
    networks:
      - elastic
  coordinator:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    env_file: docker/elasticsearch.env
    environment:
      - node.name=coordinator
    volumes:
      - ./docker/build-certs/pki/intermediate/certs/coordinator.cert.pem:/usr/share/elasticsearch/config/pki/coordinator.cert.pem
      - ./docker/build-certs/pki/intermediate/private/coordinator.key.pem:/usr/share/elasticsearch/config/pki/coordinator.key.pem
      - ./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem:/usr/share/elasticsearch/config/pki/ca.cert.pem
      - ./docker/coordinator.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elastic-healthcheck.sh:/bin/elastic-healthcheck.sh
      - data06:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs
  data02:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs
  data03:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs
  data04:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs
  data05:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs
  data06:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs
  plugins:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/nfs

networks:
  elastic:
    driver: overlay
    name: elastic