---
version: '3'

services:

  elasticsearch:
    extends:
      file: elasticsearch/docker-compose.yml
      service: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - 9200:9200

networks:
  elastic:
    driver: bridge