---
version: '3'

services:

  elasticsearch:
    extends:
      file: elasticsearch/docker-compose.yml
      service: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - 9200:9200

  kibana:
    extends:
      file: kibana/docker-compose.yml
      service: kibana
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - server.name=kibana
    networks:
      - elastic
  
  logstash:
    extends:
      file: logstash/docker-compose.yml
      service: logstash
    container_name: logstash
    networks:
      - elastic

networks:
  elastic:
    driver: bridge