################### Dynamicbeat Configuration Example #########################

############################# Dynamicbeat ######################################

dynamicbeat:
  # Defines how often checks will be executed
  period: 15s

  # Defines how often check definitions and attributes will be read from elasticsearch
  update_period: 1m

  # Where check definitions will be read from
  check_source:
    # List of Elasticsearch hosts to query
    hosts:
      - "https://localhost:9200"
    
    # Credentials used by this beat to read check definitions
    username: root 
    password: changeme

    # Whether to verify SSL/TLS certificates, if HTTPS is used
    verify_certs: false

    # The index that check definitions will be read from
    #index: checks

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5454"]

  ssl.verification_mode: full
  ssl.enabled: true

  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ["./docker/build-certs/pki/intermediate/certs/ca-chain.cert.pem"]

  # Certificate for SSL client authentication
  ssl.certificate: "./docker/build-certs/pki/intermediate/certs/beat.cert.pem"

  # Client Certificate Key
  ssl.key: "./docker/build-certs/pki/intermediate/private/beat.key.pem"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~