---
version: '3.7'
services:

  dynamicbeat-ci:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: ci
    environment:
      GOPATH: /home/scorestack/go
    image: dynamicbeat-ci:latest
    volumes:
      - "../:/home/scorestack/scorestack"
      - "./scripts/dynamicbeat:/scripts"
      - "/var/run/docker.sock:/var/run/docker.sock"
    user: scorestack

  dynamicbeat-devcontainer:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      GOPATH: /home/scorestack/go
    image: dynamicbeat-devcontainer:latest
    network_mode: host
    volumes:
      - "../:/home/scorestack/scorestack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    user: scorestack

  kibana-plugin-ci:
    image: scorestack/kibana:7.9.2
    volumes:
      - "../kibana-plugin:/home/node/kibana/plugins/scorestack"
      - "./scripts/kibana-plugin:/scripts"
    user: node

  kibana-plugin-devcontainer:
    build:
      context: .
      dockerfile: kibana-plugin.Dockerfile
      target: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
    image: kibana-plugin-devcontainer:latest
    network_mode: host
    ports:
      - 5601:5601
    volumes:
      - "../:/home/node/kibana/plugins"
    user: node