---
version: '3.7'
services:

  dynamicbeat-ci:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: ci
    image: dynamicbeat-ci:latest
    volumes:
      - "../:/home/scorestack/go/src/github.com/s-newman/scorestack"
      - "./scripts:/scripts"
    user: scorestack

  dynamicbeat-devcontainer:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
    image: dynamicbeat-devcontainer:latest
    volumes:
      - ../:/home/scorestack/go/src/github.com/s-newman/scorestack
    user: scorestack
