---
version: '3.7'
services:

  dynamicbeat-build:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: build
    entrypoint: /dynamicbeat-build.sh
    image: dynamicbeat-build:latest
    volumes:
      - "../:/home/scorestack/go/src/github.com/s-newman/scorestack"
      - "./scripts/dynamicbeat-build.sh:/dynamicbeat-build.sh"
    user: scorestack

  dynamicbeat-test:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: build
    entrypoint: /dynamicbeat-test.sh
    image: dynamicbeat-build:latest
    volumes:
      - "../:/home/scorestack/go/src/github.com/s-newman/scorestack"
      - "./scripts/dynamicbeat-test.sh:/dynamicbeat-test.sh"
    user: scorestack

  dynamicbeat-lint:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: build
    entrypoint: /dynamicbeat-lint.sh
    image: dynamicbeat-build:latest
    volumes:
      - "../:/home/scorestack/go/src/github.com/s-newman/scorestack"
      - "./scripts/dynamicbeat-test.sh:/dynamicbeat-lint.sh"
    user: scorestack

  dynamicbeat-devcontainer:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
    image: dynamicbeat-devcontainer:latest
    volumes:
      - ../:/home/scorestack/go/src/github.com/s-newman/scorestack
    user: scorestack
