---
version: '3'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - /usr/share/kibana/data
      - /usr/share/kibana/plugins