---
name: Dynamicbeat CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml up dynamicbeat-build
#      - name: Build dynamicbeat
#        run: |
#          go version
#          cd $GOPATH/src/github.com/s-newman/scorestack/dynamicbeat
#          make setup
#          go get
#          mage build
      - name: Run dynamicbeat
        run: |
          pwd
          cd src/github.com/s-newman/scorestack/dynamicbeat
          ./dynamicbeat version