---
name: Dynamicbeat CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml up dynamicbeat-build
      - name: Run dynamicbeat
        run: ./dynamicbeat/dynamicbeat version

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml up dynamicbeat-test