---
name: Dynamicbeat CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: chown -R 1000:1000 scorestack
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-ci
      - name: Build dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml run dynamicbeat-ci /scripts/dynamicbeat-build.sh
      - name: Run dynamicbeat
        run: ./dynamicbeat/dynamicbeat version

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: chown -R 1000:1000 scorestack
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-ci
      - name: Lint dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml run dynamicbeat-ci /scripts/dynamicbeat-lint.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: chown -R 1000:1000 scorestack
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-ci
      - name: Test dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml run dynamicbeat-ci /scripts/dynamicbeat-test.sh