---
name: Dynamicbeat CI

on: [push]

jobs:
  build:
    env:
      GOPATH: '/home/runner/work/scorestack/scorestack'
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/work/scorestack/scorestack/bin'
      VIRTUALENVWRAPPER_PYTHON: '/usr/bin/python2.7'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'src/github.com/s-newman/scorestack'
      - name: Install virtualenv
        run: sudo apt-get install -y virtualenv
      - name: Clone go-elasticsearch repository
        run: |
          git clone https://github.com/elastic/go-elasticsearch.git $GOPATH/src/github.com/elastic/go-elasticsearch
          cd $GOPATH/src/github.com/elastic/go-elasticsearch
          git checkout v7.5.0
      - name: Build dynamicbeat
        run: |
          cd src/github.com/s-newman/scorestack/dynamicbeat
          make setup
          go get
          mage build
      - name: Run dynamicbeat
        run: |
          cd src/github.com/s-newman/scorestack/dynamicbeat
          ./dynamicbeat version