---
name: Dynamicbeat CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-build
      - name: Build dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml up --exit-code-from dynamicbeat-build dynamicbeat-build
      - name: Run dynamicbeat
        run: ./dynamicbeat/dynamicbeat version

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint dynamicbeat
        run: docker run --vm -v dynamicbeat:/app -w /app golangci/golangci-lint:v1.25.1 golangci-lint run -v

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-test
      - name: Test dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml up --exit-code-from dynamicbeat-test dynamicbeat-test