---
name: Dynamicbeat CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build dockerfile
        run: docker build --target build -t dynamicbeat:latest dockerfiles/dynamicbeat.Dockerfile
      - name: Build dynamicbeat
        run: docker run --rm -v dynamicbeat:/go/src/github.com/s-newman/scorestack/dynamicbeat dynamicbeat:latest cd $GOPATH/src/github.com/s-newman/scorestack/dynamicbeat && make setup && go get && make build
#      - name: Build dynamicbeat
#        run: |
#          go version
#          cd $GOPATH/src/github.com/s-newman/scorestack/dynamicbeat
#          make setup
#          go get
#          mage build
      - name: Run dynamicbeat
        run: |
          pwd
          cd src/github.com/s-newman/scorestack/dynamicbeat
          ./dynamicbeat version