---
name: Kibana Plugin

on:
  push:
    branches-ignore:
      - gh-pages

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: sudo chown -R 1000:1000 .
      - name: Pull container image
        run: docker pull scorestack/kibana:7.9.2
      - name: Lint kibana plugin
        run: docker-compose -f dockerfiles/docker-compose.yml run kibana-plugin-ci /scripts/lint.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: sudo chown -R 1000:1000 .
      - name: Pull container image
        run: docker pull scorestack/kibana:7.9.2
      - name: Test kibana plugin
        run: docker-compose -f dockerfiles/docker-compose.yml run kibana-plugin-ci /scripts/test.sh